# Generated by Django 3.1.5 on 2021-01-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarRecord',
            fields=[
                ('dataset', models.CharField(max_length=30)),
                ('pseudoid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('camp', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('birthyear', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('originalstate', models.CharField(max_length=30)),
                ('familyno', models.CharField(max_length=30)),
                ('individualno', models.CharField(max_length=30)),
                ('altfamilyid', models.CharField(max_length=30)),
                ('altindividualid', models.CharField(max_length=30)),
                ('ddrreference', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
                ('othernames', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=30)),
                ('alienregistration', models.CharField(max_length=30)),
                ('entrytype', models.CharField(max_length=30)),
                ('entrydate', models.CharField(max_length=30)),
                ('originalcity', models.CharField(max_length=30)),
                ('departuretype', models.CharField(max_length=30)),
                ('departuredate', models.CharField(max_length=30)),
                ('destinationcity', models.CharField(max_length=30)),
                ('destinationstate', models.CharField(max_length=30)),
                ('campaddress', models.CharField(max_length=30)),
                ('farlineid', models.CharField(max_length=30)),
                ('errors', models.TextField()),
            ],
            options={
                'verbose_name': 'FAR Record',
            },
        ),
        migrations.CreateModel(
            name='WraRecord',
            fields=[
                ('dataset', models.CharField(max_length=30)),
                ('pseudoid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('camp', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('birthyear', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('originalstate', models.CharField(max_length=30)),
                ('familyno', models.CharField(max_length=30)),
                ('individualno', models.CharField(max_length=30)),
                ('altfamilyid', models.CharField(max_length=30)),
                ('altindividualid', models.CharField(max_length=30)),
                ('ddrreference', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
                ('assemblycenter', models.CharField(max_length=30)),
                ('originaladdress', models.CharField(max_length=30)),
                ('birthcountry', models.CharField(max_length=30)),
                ('fatheroccupus', models.CharField(max_length=30)),
                ('fatheroccupabr', models.CharField(max_length=30)),
                ('yearsschooljapan', models.CharField(max_length=30)),
                ('gradejapan', models.CharField(max_length=30)),
                ('schooldegree', models.CharField(max_length=30)),
                ('yearofusarrival', models.CharField(max_length=30)),
                ('timeinjapan', models.CharField(max_length=30)),
                ('notimesinjapan', models.CharField(max_length=30)),
                ('ageinjapan', models.CharField(max_length=30)),
                ('militaryservice', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('ethnicity', models.CharField(max_length=30)),
                ('birthplace', models.CharField(max_length=30)),
                ('citizenshipstatus', models.CharField(max_length=30)),
                ('highestgrade', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('occupqual1', models.CharField(max_length=30)),
                ('occupqual2', models.CharField(max_length=30)),
                ('occupqual3', models.CharField(max_length=30)),
                ('occuppotn1', models.CharField(max_length=30)),
                ('occuppotn2', models.CharField(max_length=30)),
                ('filenumber', models.CharField(max_length=30)),
                ('errors', models.TextField()),
            ],
            options={
                'verbose_name': 'WRA Record',
            },
        ),
    ]
