# Generated by Django 3.1.5 on 2021-02-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0005_auto_20210201_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farrecord',
            old_name='far_id',
            new_name='far_record_id',
        ),
    ]
