# Generated by Django 3.1.5 on 2021-02-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0006_auto_20210201_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.CharField(help_text='ID of facility where detained', max_length=30, primary_key=True, serialize=False, verbose_name='Facility ID')),
                ('facility_name', models.CharField(help_text='Type of facility where detained', max_length=30, verbose_name='Facility Type')),
                ('facility_type', models.CharField(help_text='Name of facility where detained', max_length=30, verbose_name='Facility Name')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_id', models.CharField(help_text='Names Registry unique identifier', max_length=30, verbose_name='Names Registry ID')),
                ('family_name', models.CharField(help_text='Preferred family or last name', max_length=30, verbose_name='Last Name')),
                ('given_name', models.CharField(help_text='Preferred given or first name', max_length=30, verbose_name='First Name')),
                ('given_name_alt', models.TextField(blank=True, help_text='List of alternative first names', max_length=30, null=True, verbose_name='Alternative First Names')),
                ('other_names', models.TextField(blank=True, help_text='List of other names', max_length=30, null=True, verbose_name='Other Names')),
                ('middle_name', models.CharField(blank=True, help_text='Middle name or initial', max_length=30, null=True, verbose_name='Middle Name')),
                ('prefix_name', models.CharField(blank=True, help_text='Professional/titular prefix. E.g., "Dr.", "Rev."', max_length=30, null=True, verbose_name='Name Prefix')),
                ('suffix_name', models.CharField(blank=True, help_text='Name suffix. E.g., "Jr.", "Esq."', max_length=30, null=True, verbose_name='Name Suffix')),
                ('jp_name', models.CharField(blank=True, help_text='Name in kana', max_length=30, null=True, verbose_name='Japanese Name')),
                ('preferred_name', models.CharField(help_text='Preferred form of full name for display', max_length=30, verbose_name='Preferred Full Name')),
                ('birth_date', models.DateField(blank=True, help_text='Full birthdate', max_length=30, null=True, verbose_name='Date of Birth')),
                ('birth_date_text', models.CharField(blank=True, help_text='Text representation of birthdate, if necessary', max_length=30, null=True, verbose_name='Birthdate Text')),
                ('birth_place', models.CharField(blank=True, help_text='Place of birth', max_length=30, null=True, verbose_name='Birthplace')),
                ('death_date', models.DateField(blank=True, help_text='Date of death', max_length=30, null=True, verbose_name='Date of Death')),
                ('death_date_text', models.CharField(blank=True, help_text='Text representation of death date, if necessary', max_length=30, null=True, verbose_name='Death Date Text')),
                ('wra_family_no', models.CharField(blank=True, help_text='WRA-assigned family number', max_length=30, null=True, verbose_name='Family Number')),
                ('wra_individual_no', models.CharField(blank=True, help_text='WRA-assigned individual number', max_length=30, null=True, verbose_name='Individual Number')),
                ('citizenship', models.CharField(help_text='Country of citizenship', max_length=30, verbose_name='Country of Citizenship')),
                ('alien_registration_no', models.CharField(blank=True, help_text='INS-assigned alien registration number', max_length=30, null=True, verbose_name='Alien Registration Number')),
                ('gender', models.CharField(help_text='Gender', max_length=30, verbose_name='Gender')),
                ('preexclusion_residence_city', models.CharField(blank=True, help_text='Last city of residence prior to exclusion', max_length=30, null=True, verbose_name='Pre-exclusion City')),
                ('preexclusion_residence_state', models.CharField(blank=True, help_text='Last state of residence prior to exclusion', max_length=30, null=True, verbose_name='Pre-exclusion State')),
                ('postexclusion_residence_city', models.CharField(blank=True, help_text='City of residence immediately following detention', max_length=30, null=True, verbose_name='Post-detention City')),
                ('postexclusion_residence_state', models.CharField(blank=True, help_text='State of residence immediately following detention', max_length=30, null=True, verbose_name='Post-detention State')),
                ('exclusion_order_title', models.CharField(blank=True, help_text='Name of U.S. Army exclusion order', max_length=30, null=True, verbose_name='Exclusion Order')),
                ('exclusion_order_id', models.CharField(blank=True, help_text='Order ID ', max_length=30, null=True, verbose_name='Exclusion Order ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PersonFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Date of entry to detention facility', verbose_name='Facility Entry Date')),
                ('exit_date', models.DateField(help_text='Date of exit from detention facility', verbose_name='Facility Exit Date')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='names.facility')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='names.person')),
            ],
        ),
    ]
