# Generated by Django 3.1.5 on 2021-02-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0007_facility_person_personfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='farrecord',
            name='person',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='names.person'),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='wrarecord',
            name='person',
            field=models.ForeignKey(blank=1, null=1, on_delete=django.db.models.deletion.DO_NOTHING, to='names.person'),
            preserve_default=1,
        ),
    ]
