# Generated by Django 3.1.5 on 2021-02-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0008_auto_20210204_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(help_text='Name of facility where detained', max_length=30, verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(help_text='Type of facility where detained', max_length=30, verbose_name='Facility Type'),
        ),
    ]
