# Generated by Django 3.1.5 on 2021-02-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0009_auto_20210204_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facility',
            field=models.ManyToManyField(through='names.PersonFacility', to='names.Facility'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='entry_date',
            field=models.DateField(blank=1, help_text='Date of entry to detention facility', verbose_name='Facility Entry Date'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='exit_date',
            field=models.DateField(blank=1, help_text='Date of exit from detention facility', verbose_name='Facility Exit Date'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='names.facility'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='names.person'),
        ),
    ]
