# Generated by Django 3.1.5 on 2021-02-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('names', '0010_auto_20210204_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='model',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='record_id',
        ),
        migrations.AddField(
            model_name='revision',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='object_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
