# Generated by Django 3.1.6 on 2021-02-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0011_auto_20210205_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facility',
            field=models.ManyToManyField(related_name='facilities', through='names.PersonFacility', to='names.Facility'),
        ),
    ]
