# Generated by Django 3.2.6 on 2021-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0012_auto_20210222_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='nr_id',
            field=models.CharField(help_text='Names Registry unique identifier', max_length=255, primary_key=True, serialize=False, verbose_name='Names Registry ID'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wrarecord',
            name='wra_record_id',
            field=models.CharField(help_text="Derived from WRA ledger id + line id ('original_order')", max_length=255, primary_key=1, serialize=False, verbose_name='WRA Record ID'),
        ),
    ]
