# Generated by Django 3.2.6 on 2021-08-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0013_auto_20210805_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farrecord',
            old_name='alien_registration',
            new_name='alien_registration_no',
        ),
        migrations.RenameField(
            model_name='wrarecord',
            old_name='martitalstatus',
            new_name='maritalstatus',
        ),
        migrations.RenameField(
            model_name='wrarecord',
            old_name='occupotn1',
            new_name='occuppotn1',
        ),
        migrations.RenameField(
            model_name='wrarecord',
            old_name='occupotn2',
            new_name='occuppotn2',
        ),
    ]
