# Generated by Django 3.2.6 on 2021-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0014_auto_20210805_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfacility',
            name='entry_date',
            field=models.DateField(blank=1, help_text='Date of entry to detention facility', null=1, verbose_name='Facility Entry Date'),
        ),
        migrations.AlterField(
            model_name='personfacility',
            name='exit_date',
            field=models.DateField(blank=1, help_text='Date of exit from detention facility', null=1, verbose_name='Facility Exit Date'),
        ),
    ]
