from django.db import models


class FarRecord(models.Model):
    """FAR/WRA record model
    
    m_pseudoid = m_camp + lastname + birthyear + firstname
    """
    m_dataset = models.CharField(max_length=30)
    m_pseudoid = models.CharField(max_length=30)
    m_camp = models.CharField(max_length=30)
    m_lastname = models.CharField(max_length=30)
    m_firstname = models.CharField(max_length=30)
    m_birthyear = models.CharField(max_length=30)
    m_gender = models.CharField(max_length=30)
    m_originalstate = models.CharField(max_length=30)
    m_familyno = models.CharField(max_length=30)
    m_individualno = models.CharField(max_length=30)
    m_altfamilyid = models.CharField(max_length=30)
    m_altindividualid = models.CharField(max_length=30)
    m_ddrreference = models.CharField(max_length=30)
    m_notes = models.CharField(max_length=30)
    f_othernames = models.CharField(max_length=30)
    f_maritalstatus = models.CharField(max_length=30)
    f_citizenship = models.CharField(max_length=30)
    f_alienregistration = models.CharField(max_length=30)
    f_entrytype = models.CharField(max_length=30)
    f_entrydate = models.DateField()
    f_originalcity = models.CharField(max_length=30)
    f_departuretype = models.CharField(max_length=30)
    f_departuredate = models.DateField()
    f_destinationcity = models.CharField(max_length=30)
    f_destinationstate = models.CharField(max_length=30)
    f_campaddress = models.CharField(max_length=30)
    f_farlineid = models.CharField(max_length=30)
    errors = models.TextField()


class WraRecord(models.Model):
    m_dataset = models.CharField(max_length=30)
    m_pseudoid = models.CharField(max_length=30)
    m_camp = models.CharField(max_length=30)
    m_lastname = models.CharField(max_length=30)
    m_firstname = models.CharField(max_length=30)
    m_birthyear = models.CharField(max_length=30)
    m_gender = models.CharField(max_length=30)
    m_originalstate = models.CharField(max_length=30)
    m_familyno = models.CharField(max_length=30)
    m_individualno = models.CharField(max_length=30)
    m_altfamilyid = models.CharField(max_length=30)
    m_altindividualid = models.CharField(max_length=30)
    m_ddrreference = models.CharField(max_length=30)
    m_notes = models.CharField(max_length=30)
    w_assemblycenter = models.CharField(max_length=30)
    w_originaladdress = models.CharField(max_length=30)
    w_birthcountry = models.CharField(max_length=30)
    w_fatheroccupus = models.CharField(max_length=30)
    w_fatheroccupabr = models.CharField(max_length=30)
    w_yearsschooljapan = models.CharField(max_length=30)
    w_gradejapan = models.CharField(max_length=30)
    w_schooldegree = models.CharField(max_length=30)
    w_yearofusarrival = models.CharField(max_length=30)
    w_timeinjapan = models.CharField(max_length=30)
    w_notimesinjapan = models.CharField(max_length=30)
    w_ageinjapan = models.CharField(max_length=30)
    w_militaryservice = models.CharField(max_length=30)
    w_maritalstatus = models.CharField(max_length=30)
    w_ethnicity = models.CharField(max_length=30)
    w_birthplace = models.CharField(max_length=30)
    w_citizenshipstatus = models.CharField(max_length=30)
    w_highestgrade = models.CharField(max_length=30)
    w_language = models.CharField(max_length=30)
    w_religion = models.CharField(max_length=30)
    w_occupqual1 = models.CharField(max_length=30)
    w_occupqual2 = models.CharField(max_length=30)
    w_occupqual3 = models.CharField(max_length=30)
    w_occuppotn1 = models.CharField(max_length=30)
    w_occuppotn2 = models.CharField(max_length=30)
    w_filenumber = models.CharField(max_length=30)
    errors = models.TextField()
